### ISSUE TITLE
See what can be salvaged/implemented from the "histogram and table" branch of the app

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth-multiplayer-data-dashboard#8]
### Description

The context is this branch: https://github.com/wesnoth/wesnoth-multiplayer-data-dashboard/tree/Table-and-Figures-Combined-early-build

Initially, when this web app was exposed to the public, the app didn't perform well in certain conditions, such as when a wide date range was selected. To mitigate the problem, the kind of data query being made was reworked to be more lightweight by requesting for only aggregate data instead of a complete set of data over the specified date range. The PR of the rework is https://github.com/wesnoth/wesnoth-multiplayer-data-dashboard/pull/4.

Actions that can be done or tried
- [ ] It's probably worth consulting the Plotly Dash community forum if they have any ideas regarding this
- [ ] Try [memray](https://github.com/bloomberg/memray), or some other profiler, to collect more precise data on what was bogging down the original version.
- [ ] Reimplement the histogram but use a method in sql that also still fetches aggregate instead of complete data for this. Kind of thing this possibly refers to is [this](https://popsql.com/sql-templates/analytics/how-to-create-histograms-in-sql), or maybe [this](https://mode.com/blog/how-to-make-box-and-whisker-plot-sql).
- [ ] Reimplement the histogram and table exactly, in a separate page or tab of the app, but limit the input range of the query to never exceed the hardware limitations of the server. The exact limit will need to be determined.

**Comment by soliton-** [comment]
IMO the last option is the way to go.

There is nothing wrong in principle in working with the complete data but it should not be mixed in with aggregate uses. Or more importantly the complete data should not be mixed in if the user perhaps just wants to see the aggregates since that just wastes a lot of resources. The other way around is less of an issue.

A page processing complete data could for example be restricted to handle at most a weeks worth of data or be limited to 10000 rows or so.

**Comment by max-torch** [comment]
Closed by #15

**Comment by max-torch** [comment]
Closed by https://github.com/wesnoth/wesnoth-multiplayer-data-dashboard/pull/15
